# Generated by Django 6.0.3 on 2026-05-18 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lf_itse', '0003_alter_inspector_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoprocedimientotupa',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
