# Generated by Django 6.0.3 on 2026-06-02 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lf_itse', '0004_tipoprocedimientotupa_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLetrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipos_letrero',
            },
        ),
        migrations.RemoveField(
            model_name='licenciafuncionamiento',
            name='fecha_digitacion',
        ),
        migrations.AddField(
            model_name='licenciafuncionamiento',
            name='tipo_letrero',
            field=models.ForeignKey(db_column='tipo_letrero_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='app_lf_itse.tipoletrero'),
            preserve_default=False,
        ),
    ]
